sudo: required
services:
    - docker
before_install:
    - docker build -t boonsiangteh/multi-client -f ./client/Dockerfile.dev ./client
script:
    - docker run boonsiangteh/multi-client npm test -- --coverage --ci

after_success:
    - docker build -t boonsiangteh/multi-client ./client
    - docker build -t boonsiangteh/multi-worker ./worker
    - docker build -t boonsiangteh/multi-server ./server
    - docker build -t boonsiangteh/multi-nginx ./nginx
    # login to docker hub and push images to docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push boonsiangteh/multi-client
    - docker push boonsiangteh/multi-worker
    - docker push boonsiangteh/multi-server
    - docker push boonsiangteh/multi-nginx
